service: legacy

provider:
  name: aws
  runtime: nodejs6.10
  stage: demo

functions:
  get:
    handler: inventory.get
    events:
      - http:
          path: inventory/{id}
          method: get
          cors: true
